### ISSUE TITLE
Transfer Suppressor.jl to JuliaIO.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaIO/Roadmap#2]
Reference:

* [Move Suppressor.jl to JuliaIO?](https://discourse.julialang.org/t/move-suppressor-jl-to-juliaio/8625)

**Comment by Ismael-VC** [comment]
It seems that I need to be part of the organization temporarily in order to request the transfer?

**Comment by SimonDanisch** [comment]
i invited you :)
